### ISSUE TITLE
Show GPS altitude

### ISSUE THREAD

**Issue by tiffiw** [Pygmalion69/OpenTopoMapViewer#8]
The app is really very simple and that makes it so cool,
Would it be able to show somewhere also the recent GPS altitude and not only the location? That would help a lot navigation in the mountains. I assume it is quite easy to obtain in addition to the position.
Many thanks
Martin

**Comment by Pygmalion69** [comment]
Since GPS reports the altitude relative to the WGS84 ellipsoid (as explained here: https://stackoverflow.com/a/2797026/959505 ) I used the NMEA string to obtain the actual elevation (meters above mean sea level). It doesn't turn out to be very accurate, though.

For now I'm displaying it in a dialog (location detail).
